'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),path=require('node:path');
const {createServer}=require('../server');

async function start(){const root=path.resolve(__dirname,'..'),created=createServer({root,publicDir:path.join(root,'public'),port:0,hintSecret:'test-hint-secret',clockSeconds:5,seatHoldMs:5000,roomIdleMs:60000});await new Promise(resolve=>created.server.listen(0,'127.0.0.1',resolve));return {...created,base:`http://127.0.0.1:${created.server.address().port}`};}
const post=(base,path,body,headers={})=>fetch(base+path,{method:'POST',headers:{'content-type':'application/json',...headers},body:JSON.stringify(body)});
test('health, HTML and security headers are served',async t=>{const env=await start();t.after(()=>new Promise(resolve=>env.server.close(resolve)));const health=await fetch(env.base+'/api/health');assert.equal(health.status,200);assert.equal((await health.json()).version,'2.1.0');const page=await fetch(env.base+'/');assert.equal(page.status,200);assert.match(page.headers.get('content-security-policy'),/worker-src 'self'/);assert.match(await page.text(),/青黛棋院/);});
test('privileged engine requires a signed cookie',async t=>{const env=await start();t.after(()=>new Promise(resolve=>env.server.close(resolve)));assert.equal((await fetch(env.base+'/js/ai.js')).status,404);const unlock=await post(env.base,'/api/hint/unlock',{key:'test-hint-secret'});assert.equal(unlock.status,200);const cookie=unlock.headers.get('set-cookie').split(';')[0];const status=await (await fetch(env.base+'/api/hint/status',{headers:{cookie}})).json();assert.equal(status.authorized,true);assert.equal((await fetch(env.base+'/js/ai.js',{headers:{cookie}})).status,200);const game=await fetch(env.base+'/game.html',{headers:{cookie}});assert.match(await game.text(),/hint\.js\?v=3/);});
test('join API assigns two different sides and rejects a third seat',async t=>{const env=await start();t.after(()=>new Promise(resolve=>env.server.close(resolve)));const a=await (await post(env.base,'/api/join',{room:'集成测试',name:'甲'})).json(),b=await (await post(env.base,'/api/join',{room:'集成测试',name:'乙'})).json();assert.equal(a.side,1);assert.equal(b.side,-1);const third=await post(env.base,'/api/join',{room:'集成测试',name:'丙'});assert.equal(third.status,409);});
