'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {RoomService,RoomError}=require('../src/rooms');

function pair(){const service=new RoomService({clockSeconds:5,seatHoldMs:5000}),red=service.join({room:'棋局',name:'红'}),black=service.join({room:'棋局',name:'黑'}),room=service.get('棋局');room.players.get(red.sid).online=true;room.players.get(black.sid).online=true;room.started=true;return {service,room,red,black};}
test('first seat is red, second is black, third is rejected',t=>{const {service,red,black}=pair();t.after(()=>service.close());assert.equal(red.side,1);assert.equal(black.side,-1);assert.throws(()=>service.join({room:'棋局',name:'第三人'}),error=>error instanceof RoomError&&error.status===409);});
test('server validates turns and applies a legal move',t=>{const {service,room,red,black}=pair();t.after(()=>service.close());assert.throws(()=>service.move({room:'棋局',sid:black.sid,mv:{fr:{r:6,c:0},to:{r:5,c:0}}}),/还没轮到你/);service.move({room:'棋局',sid:red.sid,mv:{fr:{r:3,c:0},to:{r:4,c:0}}});assert.equal(room.board[4][0],'P0');assert.equal(room.turn,-1);assert.equal(room.history.length,1);});
test('undo returns to requester previous turn',t=>{const {service,room,red,black}=pair();t.after(()=>service.close());service.move({room:'棋局',sid:red.sid,mv:{fr:{r:3,c:0},to:{r:4,c:0}}});service.move({room:'棋局',sid:black.sid,mv:{fr:{r:6,c:0},to:{r:5,c:0}}});const result=service.undoRequest({room:'棋局',sid:red.sid});assert.equal(result.pending,true);service.undoAccept({room:'棋局',sid:black.sid});assert.equal(room.history.length,0);assert.equal(room.turn,1);assert.equal(room.board[3][0],'P0');});
test('restart swaps colors and preserves optional clock setting',t=>{const {service,room,red}=pair();t.after(()=>service.close());service.toggleClock({room:'棋局',sid:red.sid});assert.equal(room.clock.enabled,true);service.restart({room:'棋局',sid:red.sid});assert.equal(room.players.get(red.sid).side,-1);assert.equal(room.turn,1);assert.equal(room.history.length,0);assert.equal(room.clock.enabled,true);});
