'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {rules:R}=require('../public/js/rules');

test('standard board has 32 pieces and independent rows',()=>{const a=R.initialBoard(),b=R.initialBoard();assert.equal(a.flat().filter(Boolean).length,32);a[0][0]=null;assert.equal(b[0][0],'R0');});
test('horse leg, elephant river and palace boundaries are enforced',()=>{const board=R.initialBoard();assert.ok(R.legalMovesFrom(board,{r:0,c:1}).some(m=>m.to.r===2&&m.to.c===2));board[1][1]='P9';assert.ok(!R.legalMovesFrom(board,{r:0,c:1}).some(m=>m.to.r===2&&m.to.c===2));assert.ok(R.legalMovesFrom(board,{r:0,c:2}).every(m=>m.to.r<=4));assert.ok(R.legalMovesFrom(board,{r:0,c:4}).every(m=>R.inPalace(m.to.r,m.to.c)));});
test('cannon requires exactly one screen to capture',()=>{const board=Array.from({length:10},()=>Array(9).fill(null));board[0][4]='K0';board[9][3]='k0';board[0][0]='C0';board[2][0]='P0';board[5][0]='r0';board[7][0]='r1';const moves=R.legalMovesFrom(board,{r:0,c:0});assert.ok(moves.some(m=>m.to.r===5&&m.to.c===0));assert.ok(!moves.some(m=>m.to.r===7&&m.to.c===0));});
test('facing kings make exposing moves illegal',()=>{const board=Array.from({length:10},()=>Array(9).fill(null));board[0][4]='K0';board[9][4]='k0';board[5][4]='R0';assert.ok(!R.legalMovesFrom(board,{r:5,c:4}).some(m=>m.to.c!==4));assert.ok(R.illegalMovesFrom(board,{r:5,c:4}).some(m=>m.to.c!==4));});
test('apply and undo restore the board byte-for-byte',()=>{const board=R.initialBoard(),before=JSON.stringify(board),mv=R.legalMovesFrom(board,{r:0,c:1})[0],captured=R.applyMove(board,mv);R.undoMove(board,mv,captured);assert.equal(JSON.stringify(board),before);});
test('opening position has legal moves for both sides',()=>{const board=R.initialBoard();assert.ok(R.legalMoves(board,R.RED).length>20);assert.ok(R.legalMoves(board,R.BLACK).length>20);assert.equal(R.resultFor(board,R.RED),'playing');});
test('direct check detector covers rook, cannon, horse and pawn attacks',()=>{const make=()=>Array.from({length:10},()=>Array(9).fill(null));let board=make();board[0][4]='K0';board[9][3]='k0';board[5][4]='r0';assert.equal(R.inCheck(board,R.RED),true);board=make();board[0][4]='K0';board[9][3]='k0';board[2][4]='P0';board[5][4]='c0';assert.equal(R.inCheck(board,R.RED),true);board=make();board[0][4]='K0';board[9][3]='k0';board[2][5]='h0';assert.equal(R.inCheck(board,R.RED),true);board=make();board[0][4]='K0';board[9][3]='k0';board[1][4]='p0';assert.equal(R.inCheck(board,R.RED),true);});
